config/routes.rb
UserTimeTrack::Application.routes.draw do
  get "session/new"
  post "session/login"
  post "session/logout"
  resources :users

  root 'users#index'

  controller :users do  
   get "analytics"
   get "statistics"
   get "each_user_analytics"
   post "admin"
  end

  

end

app/models/user.rb
include Calculations
class User < ActiveRecord::Base
	has_many :user_times
	validates_format_of :username,  :with => /\A[a-zA-Z0-9]+[^\W]\z/
   validates :username,   :presence => true, :uniqueness => true 
end

app/models/user_time.rb
class UserTime < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
        @current_user =  User.find(session[:user_id]) 
  end  	

def authorize
   unless User.find_by_id(session[:user_id])
   end	
end	
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def login
  	puts "_____________________________________"
  	 if @user=User.find_by_username(params[:username])
              session[:user_id] = @user.id
             a=Time.now.to_datetime.in_time_zone('Mumbai')
             if (10<=a.hour)&&(00==a.min)
				        puts " ______________________You Logged at right time  : #{a}" 
		         else
				        puts "___________________________ You Logged late  : #{a}"
		   	     end
		   	    @user.user_times.create(:arrival_time=>a)
            if @user.present? && @user.role=="admin"
             render layout: "admin"
       
            elsif @user.present? && @user.role=="employee"
           #format.html { redirect_to users_path, notice: ' Username does not Exist ' }            
          #redirect_to "/users"
            puts @user.username

            redirect_to user_path(@user)
            else
             redirect_to "/users",:notice=> "Improper Username OR Username does not exist"

            end 
    else
          redirect_to "/users",:notice=> "Improper Username OR Username does not exist"
    end

  end

  def logout
  	  session[:user_id]=nil
      redirect_to "/users"
  end
end

app/controllers/users_controller.rb
require 'gchart'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate :page=>params[:page],:per_page=>2
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@user=current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def analytics
    @average_time= avg(UserTime.all.where("date(arrival_time)=?",DateTime.now.to_date).map{|e|e.arrival_time.in_time_zone('Mumbai').strftime("%H:%M")})
    @all_user_max_arrival_time=max_arrival_time(UserTime.all.where("date(arrival_time)=?",DateTime.now.to_date).map{|e|e.arrival_time.in_time_zone('Mumbai').strftime("%H")})
    @image_url=Gchart.line(:data => UserTime.all.where("date(arrival_time)=?",DateTime.now.to_date).map{|e|e.arrival_time.in_time_zone('Mumbai').strftime("%H:%M").to_i})


  end

   # def avg_times(var)
   #   puts "#{var}"
   #    begin
   #     grand_total=0
   #     size=var.size 
   #      puts "size #{size}"
   #     avg_minutes=var.map do|x| 
   #     hour,minute=x.split(':')
   #      puts "size1"

   #      total_minutes=hour.to_i*60+minute.to_i 
   #       puts "total_minutes #{total_minutes}"
   #      grand_total=grand_total+total_minutes
   #     end
   #        puts "avg_minutes #{avg_minutes}"
   #        puts "grand_total #{grand_total}"
   #        avg_value=grand_total/size
          
   #        average_time=avg_value.to_f/60
   #        #puts "average #{average_time}"
   #        #return average_time
   #       rescue Exception => e
   #         redirect_to "/users",:notice=> "No User Arrived Yet"
   #          #raise  ZeroDivisionError, "I am raising this exception"
   #       end 
   #  end
   
   def each_user_analytics
     @user=User.find(params[:id])
     #puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#{@user.id}"
     #puts "----------#{@each_user}"
     #return @each_user
     @each_user_average=avg(@user.user_times.map{|c|c.arrival_time.in_time_zone("Mumbai").strftime("%H:%M")})
     @user_max_arrival_time=max_arrival_time(@user.user_times.map{|c|c.arrival_time.in_time_zone("Mumbai").strftime("%H")})
     @image_url=Gchart.pie_3d(:data => @user.user_times.map{|c|c.arrival_time.in_time_zone("Mumbai").strftime("%H").to_i})

   end

   
   def max_arrival_time(var)
      freq=var.inject(Hash.new(0)){|h,v| h[v]+=1;h}
      var.sort_by{|v|freq[v]}.last           
   
   end

   def statistics
      #@user=User.find(params[:id])
      @users = User.all

      #@user=User.find(params[:id])
      # @res=@users.map do|user|
      #     @avg_state=avg_times(user.user_times.map{|e|e.arrival_time.in_time_zone("Mumbai").strftime("%H:%M")})
      #     a={user:user,time: @avg_state}
      # end  
   end
       
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<%= yield%>
<i>Welcome Admin</i><br><br>
      <% @users = User.all%>


	<table border="2">
		<tr>
     
    <th>User Name</th>
    <th>Late arrivals</th>
    <th>Delete</th>
    <th></th>
  </tr>
     <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
            <%count=0%>
        <td><% user.user_times.each do|e|%>
            <% a=e.arrival_time.in_time_zone("Mumbai").strftime("%H")%>
            <%count=count+1 if a.to_i>=11%>
            <%end%>
            <%= count %>
        </td>
        <td><%= button_to "Delete" ,{:action=> "destroy",:controller =>"users",:id=>user.id},:method=>"delete" %></td></tr>
            <% end %>
</table>
<br>
<br>

<h2><b><i><%= "Pie Chart of average employee for each employee" %></i></b></h2> 
<%= image_tag Gchart.pie_3d(:size => '400x200', :data =>UserTime.all.where("date(arrival_time)=?",DateTime.now.to_date).map{|e|e.arrival_time.in_time_zone('Mumbai').strftime("%H:%M").to_i}, :labels => ["DHH", "Rob", "Matt","1","2","3"] ) %>


<br>
OTHER ADMIN FUNCTIONALITIES :

<table border="0">
		<tr>
<th><h5><p align="right"><%= link_to 'Create NewUser', new_user_path %></align></h5></th></tr>
<tr><th><%= button_to "Logout" ,{:action=> "logout" , :controller =>"session",:method=>"post"} %></th><tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserTimeTrack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <body style="background-color:LIGHTYELLOW;"><br>

<%= yield %>

</body>
</html>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/analytics.html.erb
<h2><b><i><%= "Average Time of all the employees #{@average_time}" %></i></b></h2> 
<%= image_tag @image_url %>
</br><h2><b><i><%= "The Time when you enter in office usually around .. #{@all_user_max_arrival_time}"%></i></b></h2>

app/views/users/each_user_analytics.html.erb
<h2><b><i><%= "Welcome to #{@user.username} Attendence Tracking System !!"%></i></b></h2>
  
  <table border=1>
  <thead>
    <tr>
    <th><font color="blue">Yours Arrival Time :</font></th>
    </tr>  
   </thead>
   <tbody>  
   	  <tr>

	  <% @user.user_times.each do |c|%>
	  <td><%=c.arrival_time.in_time_zone("Mumbai")%></td>
	  
	</tr>
  <%end%>
   </tbody>
</table>

  </br><h2><b><i><font color="blue"><%= "Average Time of your is #{@each_user_average}"%></font></i></b></h2>

    </br><h2><b><i><font color="blue"><%= "The Time when you enter in office usually around .. #{@user_max_arrival_time}"%></font></i></b></h2>

<%= image_tag @image_url %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
 <CENTER><u><h1>WELCOME TO EMPLOYEES ATTENDENCE TRACKING SYSTEM</h1></u></CENTER>
<center>
<%= form_tag(controller: "session", action: "login", method: "post") do %>
      <tr>
      <b><%= label_tag(:username, "username:") %></b>
      <%= text_field_tag(:username) %>
       </tr>
       <tr>
       <%= submit_tag("Login") %>
       </tr>
<% end %>

</center>

<center><h2><font color="red"><p id="notice"><%= notice %></font><h2></p></center>

<br>
<br>
 
<h3><p align="right"><%= link_to 'Analytics', analytics_path %></align></h3>
<h3><p align="right"><%= link_to 'Statistics', statistics_path %></align></h3>
 
<h4>LOGGED EMPLOYEES</h4>

<table border=1>
  <thead>
    <tr>
      <th>Username</th>
      <th>Role</th>
      <th>ArrivalTime</th>
          </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <% if user.user_times.present? %>
      <tr>
        <td><%= link_to "#{user.username}", :action =>"each_user_analytics", :id=> user.id %></td>
        <td><%= user.role %></td>

        <td><%= user.user_times.last.arrival_time.in_time_zone("Mumbai")  %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>
<p><%= will_paginate @users %></p>

app/views/users/new.html.erb
<h4>Create New user</h4>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2><b><i><%= "Welcome #{@user.username}" %> </br> </br></br></i></b></h2>



       <%a=Time.now.in_time_zone('Mumbai')%>
       
             <%if (10<=a.hour)&&(00==a.min)%> 
				<%= " You Logged at right time  : #{a}"%> 
		     <%else%>
				<h2><font color="red"><%= "You Logged late  : #{a}"%></font><h2>
		   	 <%end%>
		   	
<% #arrival_time= Time.now %>

            


<%= button_to "Logout" ,{:action=> "logout" , :controller =>"session",:method=>"post"} %>

app/views/users/statistics.html.erb
<table border=1>
  <thead>
    <tr>
      <th>Username</th>
      <th>Number Of Late Arrivals</th>
      <th> Arrival Time</th>
      <th>Average Arrival Time</th>
      <th>Chart for Arrival Time</th>
      <th>Bonus</th>

    </tr>
  </thead>

  <tbody>
       <% @users.sort_by!{|m|m.username.downcase} %>
        <% @users.each do |user| %>
        <% if user.user_times.present? %>
      <tr>
        <td><%= user.username %></td>
            <%count=0%>
        <td><% user.user_times.each do|e|%>
            <% a=e.arrival_time.in_time_zone("Mumbai").strftime("%H")%>
            <%count=count+1 if a.to_i>=11%>
          <%end%>

             <%= count %>
        </td>
       
        <td><%= user.user_times.map{|g|g.arrival_time.in_time_zone("Mumbai").strftime("%H")}  %> </td>
        <td><%= user.avg(user.user_times.map{|k|k.arrival_time.in_time_zone("Mumbai").strftime("%H:%M")})          %></td>
        <td>   <%= image_tag Gchart.line(:data => user.user_times.map{|g|g.arrival_time.in_time_zone("Mumbai").strftime("%H").to_i}) %>
        </td>

        <td></td>

        <%end%>
        <%end%>

  </tbody>
</table>

<br>